steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/awesome-pilot-400117/text-to-speech-java:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/awesome-pilot-400117/text-to-speech-java:$COMMIT_SHA'

  # Step 3: Deploy the application to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$SERVICE_NAME'
      - '--image'
      - 'gcr.io/awesome-pilot-400117/text-to-speech-java:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1' # Replace with your desired region
      - '--allow-unauthenticated' # Remove this if you want to require authentication

substitutions:
  _PROJECT_ID: awesome-pilot-400117
  _IMAGE_NAME: text-to-speech-java
  _SERVICE_NAME: text-to-speech-java
  _COMMIT_SHA: $SHORT_SHA

images:
  - 'gcr.io/awesome-pilot-400117/text-to-speech-java:$COMMIT_SHA'
